version: '3'
services:
  app:
    container_name: superapi_app
    build: .
    command: go run main.go
    ports: 
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/superapi
    depends_on:
      - db
       
  db:
    image: postgres
    container_name: superapi_db
    environment:
      - POSTGRES_USER=${DB_USER} 
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: superapi_pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  database_postgres:
